name: OKX Scanner

on:
  schedule:
    - cron: '*/5 * * * *'   # Her 5 dakikada bir çalışır
  workflow_dispatch:          # Manuel çalıştırma butonu da olsun

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri kur
        run: pip install requests pandas tabulate

      - name: Taramayı çalıştır
        run: python okxbot.py
